// <auto-generated />
using DNet_PostgreSQL_Demonstration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DNet_PostgreSQL_Demonstration.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190602202142_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "3.0.0-preview5.19227.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DNet_PostgreSQL_Demonstration.DataContract.News", b =>
                {
                    b.Property<string>("Id");

                    b.Property<string>("AuthorId");

                    b.Property<string>("Content");

                    b.Property<string>("EditorId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("EditorId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("DNet_PostgreSQL_Demonstration.DataContract.User", b =>
                {
                    b.Property<string>("Id");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DNet_PostgreSQL_Demonstration.DataContract.News", b =>
                {
                    b.HasOne("DNet_PostgreSQL_Demonstration.DataContract.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("DNet_PostgreSQL_Demonstration.DataContract.User", "Editor")
                        .WithMany()
                        .HasForeignKey("EditorId");
                });
#pragma warning restore 612, 618
        }
    }
}
